const ADD_FRIEND = 'ADD_FRIEND';  
const STAR_FRIEND = 'STAR_FRIEND';  
const DELETE_FRIEND = 'DELETE_FRIEND';

export const types = {
	ADD_FRIEND: ADD_FRIEND,
	STAR_FRIEND: STAR_FRIEND,
	DELETE_FRIEND: DELETE_FRIEND
}